### ISSUE TITLE
[simple-hub] Error after killing

### ISSUE THREAD

**Issue by kerzhner** [statechannels/statechannels#1566]
1. Run `simple-hub` locally: `SC_ENV=virtual-funding yarn hub:watch`
1. Use control-c (on macos) to kill simple hub.

Observer the following error:
```
Events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: read EIO
    at TTY.onStreamRead (internal/stream_base_commons.js:111:27)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by snario** [comment]
I don't see this when I follow the instructions
