### ISSUE TITLE
Occasional timeout when using start-servers command

### ISSUE THREAD

**Issue by lalexgap** [statechannels/statechannels#2079]
I've seen this happen locally a couple times and recently saw it on [CI](https://app.circleci.com/pipelines/github/statechannels/monorepo/7146/workflows/c2dfc2a1-4b67-462a-9849-b4b367650a58/jobs/32537)

Rerunning it [succeeded](https://app.circleci.com/pipelines/github/statechannels/monorepo/7146/workflows/c2dfc2a1-4b67-462a-9849-b4b367650a58/jobs/32537)

```
Starting a ganache server on http://localhost:8545
 
Error: Timeout
 
    at MergeMapSubscriber.timer.pipe.mergeMap [as project] (/home/circleci/project/node_modules/wait-on/lib/wait-on.js:145:74)
 
    at MergeMapSubscriber._tryNext (/home/circleci/project/node_modules/rxjs/internal/operators/mergeMap.js:69:27)
 
    at MergeMapSubscriber._next (/home/circleci/project/node_modules/rxjs/internal/operators/mergeMap.js:59:18)
 
    at MergeMapSubscriber.Subscriber.next (/home/circleci/project/node_modules/rxjs/internal/Subscriber.js:66:18)
 
    at AsyncAction.dispatch [as work] (/home/circleci/project/node_modules/rxjs/internal/observable/timer.js:31:16)
 
    at AsyncAction._execute (/home/circleci/project/node_modules/rxjs/internal/scheduler/AsyncAction.js:71:18)
 
    at AsyncAction.execute (/home/circleci/project/node_modules/rxjs/internal/scheduler/AsyncAction.js:59:26)
 
    at AsyncScheduler.flush (/home/circleci/project/node_modules/rxjs/internal/scheduler/AsyncScheduler.js:52:32)
 
    at ontimeout (timers.js:436:11)
 
    at tryOnTimeout (timers.js:300:5)
 
```

**Comment by andrewgordstewart** [comment]
In fact, ganache does manage to start, but it then stops for some reason.

Another example is here. The [artifact](https://34462-209829093-gh.circle-artifacts.com/0/integration-test-stats) listing the running processes shows that the ganache server is running at time 93 but not at time 94.

Ganache [logs](https://34462-209829093-gh.circle-artifacts.com/0/home/circleci/project/logs/ganache.log) don't indicate anything that went wrong.
