### ISSUE TITLE
Flickering test

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/statechannels#2550]
[Test failure:](https://app.circleci.com/pipelines/github/statechannels/statechannels/8881/workflows/8c6cf822-0272-411d-9442-bc20acd40009/jobs/42148)

```
@statechannels/nitro-protocol: FAIL test/contracts/AssetHolder/claimAll.test.ts (79.11s)
@statechannels/nitro-protocol:   ● claimAll › 3. swap guarantee,             3 destinations
@statechannels/nitro-protocol:     : Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Error:
@statechannels/nitro-protocol:       59 |     ${'6. guarantee not on chain'}                     | ${{g: 5}}  | ${[]}                 | ${{A: 5, B: 5}}       | ${{A: 5}}       | ${{g: 0}} | ${{B: 5}}       | ${reason6}
@statechannels/nitro-protocol:       60 |     ${'7. swap guarantee, overfunded, 2 destinations'} | ${{g: 12}} | ${['B', 'A']}         | ${{A: 5, B: 5}}       | ${{}}           | ${{g: 2}} | ${{A: 5, B: 5}} | ${undefined}
@statechannels/nitro-protocol:     > 61 |     ${'8. underspecified guarantee, overfunded      '} | ${{g: 12}} | ${['B']}              | ${{A: 5, B: 5}}       | ${{}}           | ${{g: 2}} | ${{A: 5, B: 5}} | ${undefined}
@statechannels/nitro-protocol:          |                                                                                                                                                                                  ^
@statechannels/nitro-protocol:       62 |   `(
@statechannels/nitro-protocol:       63 |     '$name',
@statechannels/nitro-protocol:       64 |     async ({
@statechannels/nitro-protocol:       at new Spec (../../node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
@statechannels/nitro-protocol:           at Array.forEach (<anonymous>)
@statechannels/nitro-protocol:       at Suite.<anonymous> (test/contracts/AssetHolder/claimAll.test.ts:61:178)
```

[Re-running it](https://app.circleci.com/pipelines/github/statechannels/statechannels/8881/workflows/5822789f-6044-4ba6-bd6e-4cd3e1dd5576/jobs/42149), the test passes:
```
@statechannels/nitro-protocol: PASS test/contracts/AssetHolder/claimAll.test.ts (67.933s)
```

Is this because the 5 second timeout is too short, and that test run happened to go over the edge? Note that the passing test took ~15% less time than the failing test.

**Comment by andrewgordstewart** [comment]
This seems infrequent enough to close.
