### ISSUE TITLE
Violation of unique constraint "objectives_pkey"

### ISSUE THREAD

**Issue by That3Percent** [statechannels/statechannels#2866]
**Describe the bug :bug:**
Exception thrown due to unique constraint violation:

```
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
UniqueViolationError: insert into "objectives" ("data", "objective_id", "status", "type") values ($1, $2, $3, $4) returning "objective_id" - duplicate key value violates unique constraint "objectives_pkey"
    at wrapError (/Users/zacharyburns/Documents/git/the-graph/gateway/node_modules/db-errors/lib/dbErrors.js:19:14)
    at handleExecuteError (/Users/zacharyburns/Documents/git/the-graph/gateway/node_modules/objection/lib/queryBuilder/QueryBuilder.js:1506:32)
    at QueryBuilder.execute (/Users/zacharyburns/Documents/git/the-graph/gateway/node_modules/objection/lib/queryBuilder/QueryBuilder.js:687:20)
From previous event:
    at /Users/zacharyburns/Documents/git/the-graph/gateway/node_modules/knex/lib/transaction.js:66:32
    at /Users/zacharyburns/Documents/git/the-graph/gateway/node_modules/knex/lib/transaction.js:229:24
    at processImmediate (internal/timers.js:456:21)
From previous event:
    at Transaction.acquireConnection (/Users/zacharyburns/Documents/git/the-graph/gateway/node_modules/knex/lib/transaction.js:227:8)
    at new Transaction (/Users/zacharyburns/Documents/git/the-graph/gateway/node_modules/knex/lib/transaction.js:57:26)
    at Client_PG.transaction (/Users/zacharyburns/Documents/git/the-graph/gateway/node_modules/knex/lib/client.js:124:12)
    at Function.transactor.transaction (/Users/zacharyburns/Documents/git/the-graph/gateway/node_modules/knex/lib/transaction.js:266:24)
    at Function.insert (/Users/zacharyburns/Documents/git/the-graph/gateway/node_modules/@statechannels/server-wallet/lib/src/models/objective.js:51:19)
    at Store.addObjective (/Users/zacharyburns/Documents/git/the-graph/gateway/node_modules/@statechannels/server-wallet/lib/src/wallet/store.js:266:46)
    at async store.lockApp.CloseChannel.CloseChannelError.channelId.channelId (/Users/zacharyburns/Documents/git/the-graph/gateway/node_modules/@statechannels/server-wallet/lib/src/wallet/wallet.js:272:13)
    at async time (/Users/zacharyburns/Documents/git/the-graph/gateway/node_modules/@statechannels/server-wallet/lib/src/metrics.js:55:16)
```

**To Reproduce**
Occurred when running a The Graph Gateway. When restarting, this exception occurs again. Unsure how to recreate this state from scratch.

**Comment by That3Percent** [comment]
Database dump:

[gateway-local.txt](https://github.com/statechannels/statechannels/files/5524951/gateway-local.txt)

**Comment by Jannis** [comment]
Sentry issue with additional information: https://sentry.io/organizations/graphprotocol/issues/2023182977/?project=5501619&query=is%3Aunresolved&statsPeriod=90d

**Comment by lalexgap** [comment]
Closing as this looks to be stale.
