### ISSUE TITLE
Can receipt managers submit transactions?

### ISSUE THREAD

**Issue by kerzhner** [statechannels/statechannels#3204]
**Task:** Confirm that the receipt manager can successfully submit concludeAndWithdraw transactions in our e2e tests.

There is evidence that indexers are not submitting `concludeAndWithdraw` transactions. Investigate if that is due to indexers always (or almost always) losing the race to submit a transaction or because the receipt manager is not configured for the chain service to submit transactions.

I think the sequence of tasks for this investigation is:
- Can we observe the indexer chain service submitting concludeAndWithdraw transaction in graph-payment e2e tests?
- If yes, then either
  - conditions in the graph network are different so that the gateway wins the race to submit a transaction most of the time
  - indexers configure receipt-managers in a way where the indexer chain service is unable to submit a transaction.

**Comment by kerzhner** [comment]
At the moment, I am not able to run `graph-payments` tests locally.
```
➜  e2e-testing git:(main) ✗ ./scripts/run-local.sh 
yarn run v1.22.4
warning package.json: No license field
$ npx ts-node ./scripts/db-utils.ts create_schema postgresql://postgres@localhost/payer
Using db connection {"user":"postgres","password":"","port":null,"host":"localhost","database":"payer"}
Creating schema if needed
✨  Done in 1.91s.
yarn run v1.22.4
$ yarn test:e2e
$ FUNDING_STRATEGY=Fake jest e2e.test.ts --ci --runInBand
ts-jest[versions] (WARN) Version 4.1.2 of typescript installed has not been tested with ts-jest. If you're experiencing issues, consider using a supported version (>=3.8.0 <4.0.0-0). Please do not report issues in ts-jest if you are using unsupported versions.
(node:28848) V8: graph-payments/node_modules/rustbn.js/lib/index.asm.js:2 Linking failure in asm.js: Unexpected stdlib member
 FAIL  __tests__/e2e.test.ts (12.661 s)
  Payment & Receipt Managers E2E
    ✕ Can create and pay with 2 allocations (6053 ms)
    ○ skipped Can remove 2 allocations using syncAllocations
    ○ skipped Payment and Receipt can get back in sync if indexer offline
    ○ skipped Payment and Receipt can get back in sync if payer missed receipt

  ● Payment & Receipt Managers E2E › Can create and pay with 2 allocations

    Request failed with status code 406

      at createError (../../node_modules/axios/lib/core/createError.js:16:15)
      at settle (../../node_modules/axios/lib/core/settle.js:17:12)
      at IncomingMessage.handleStreamEnd (../../node_modules/axios/lib/adapters/http.js:244:11)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 3 skipped, 4 total
Snapshots:   0 total
Time:        12.7 s
```

**Comment by wunnaii** [comment]
Not part of the generic solution
