### ISSUE TITLE
[nitro-protocol] Code formatter for solidity

### ISSUE THREAD

**Issue by kerzhner** [statechannels/statechannels#36]
Status quo: `prettier-plugin-solidity` is showing errors for valid solidity code. We should either figure out how to fix this issue with this package, or find another package that formats or lints solidity. The error is:
```
$ npx prettier --check '{contracts,src,test}/**/*.{ts,tsx,sol}'
Checking formatting...
contracts/AssetHolder.sol[error] contracts/AssetHolder.sol: ParserError: missing ';' at '(' (34:63)
[error]     at Object.parse (/Users/misha/dev/statechannels/nitro-protocol/node_modules/solidity-parser-antlr/dist/index.js:79:11)
[error]     at Object.parse (/Users/misha/dev/statechannels/nitro-protocol/node_modules/prettier-plugin-solidity/src/parser.js:16:25)
[error]     at Object.parse$2 [as parse] (/Users/misha/dev/statechannels/nitro-protocol/node_modules/prettier/bin-prettier.js:10631:19)
[error]     at coreFormat (/Users/misha/dev/statechannels/nitro-protocol/node_modules/prettier/bin-prettier.js:13890:23)
[error]     at format (/Users/misha/dev/statechannels/nitro-protocol/node_modules/prettier/bin-prettier.js:14148:73)
[error]     at formatWithCursor (/Users/misha/dev/statechannels/nitro-protocol/node_modules/prettier/bin-prettier.js:14164:12)
[error]     at Object.formatWithCursor (/Users/misha/dev/statechannels/nitro-protocol/node_modules/prettier/bin-prettier.js:42758:15)
[error]     at format$1 (/Users/misha/dev/statechannels/nitro-protocol/node_modules/prettier/bin-prettier.js:44127:21)
[error]     at /Users/misha/dev/statechannels/nitro-protocol/node_modules/prettier/bin-prettier.js:44322:16
[error]     at /Users/misha/dev/statechannels/nitro-protocol/node_modules/prettier/bin-prettier.js:44262:14
```

**Comment by snario** [comment]
That blocker seems to have been closed (ignored?)
