### ISSUE TITLE
If both participants use same channel constants we can get duplicate channelIds

### ISSUE THREAD

**Issue by lalexgap** [statechannels/statechannels#3652]
**Describe the bug**
If two participants both try to create channels at the same time using the same  `participants, chainId, challengeDuration, appDefinition` then both participants could generate the same channelId when trying to create the channel.

In the load testing, this manifested itself as `UniqueViolationErrors`:

```
 type: 'InternalError',
  error: UniqueViolationError: insert into "channels" ("app_definition", "chain_id", "challenge_duration", "channel_id", "channel_nonce", "funding_strategy", "is_ledger_channel", "participants", "signing_address", "vars") values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) returning * - duplicate key value violates unique constraint "channels_channel_id_unique"
      at wrapError (/Users/lagap/code/statechannels/node_modules/db-errors/lib/dbErrors.js:19:14)
      at handleExecuteError (/Users/lagap/code/statechannels/node_modules/objection/lib/queryBuilder/QueryBuilder.js:1506:32)
      at QueryBuilder.execute (/Users/lagap/code/statechannels/node_modules/objection/lib/queryBuilder/QueryBuilder.js:687:20)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5) {
    nativeError: error: insert into "channels" ("app_definition", "chain_id", "challenge_duration", "channel_id", "channel_nonce", "funding_strategy", "is_ledger_channel", "participants", "signing_address", "vars") values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) returning * - duplicate key value violates unique constraint "channels_channel_id_unique"
        at Connection.parseE (/Users/lagap/code/statechannels/node_modules/pg/lib/connection.js:604:13)
        at Connection.parseMessage (/Users/lagap/code/statechannels/node_modules/pg/lib/connection.js:403:19)
        at Socket.<anonymous> (/Users/lagap/code/statechannels/node_modules/pg/lib/connection.js:123:22)
        at Socket.emit (events.js:310:20)
        at Socket.EventEmitter.emit (domain.js:482:12)
        at addChunk (_stream_readable.js:286:12)
        at readableAddChunk (_stream_readable.js:268:9)
        at Socket.Readable.push (_stream_readable.js:209:10)
        at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
      length: 288,
      severity: 'ERROR',
      code: '23505',
      detail: 'Key (channel_id)=(0x061ab7c12a36b9df086e7522ed8b439557ec59df43285243cb199db3c2abe711) already exists.',
      hint: undefined,
      position: undefined,
      internalPosition: undefined,
      internalQuery: undefined,
      where: undefined,
      schema: 'public',
      table: 'channels',
      column: undefined,
      dataType: undefined,
      constraint: 'channels_channel_id_unique',
      file: 'nbtinsert.c',
      line: '656',
      routine: '_bt_check_unique'
    },
    client: 'postgres',
    table: 'channels',
    columns: [ 'channel_id' ],
    constraint: 'channels_channel_id_unique',
    schema: undefined
  }
```

One easy way to work around this is to re-order participants depending on who is calling create channel.

IE: A.createChannel should use participants [A,B] while B.createChannel uses [B,A]

**To Reproduce**
See the test [here](https://github.com/statechannels/statechannels/blob/ag/simul-create-test/packages/server-wallet/src/__chain-test__/simul-create-channel.test.ts#L1:L1)

**Comment by andrewgordstewart** [comment]
This seems like a race condition that the wallet should handle gracefully.

> One easy way to work around this is to re-order participants depending on who is calling create channel.
> IE: A.createChannel should use participants [A,B] while B.createChannel uses [B,A]

I'm not sure I understand this solution. Are you suggesting one of these?
1. when an application asks its wallet to create a channel, it should set its user as the first participant _by convention_
2. when an application asks its wallet to create a channel, its wallet automatically sets its user as the first participant
3. when an application asks its wallet to create a channel, its wallet  enforces that its user is the first participant

I don't think either of these solutions are great, given the current round-robin turn-taking semantics. The first peer in a 2-party channel always moves on turn 4; what if A wants to create an app channel where B moves first?

**Comment by lalexgap** [comment]
> I'm not sure I understand this solution. Are you suggesting one of these?
> 
> 1. when an application asks its wallet to create a channel, it should set its user as the first participant _by convention_
> 2. when an application asks its wallet to create a channel, its wallet automatically sets its user as the first participant
> 3. when an application asks its wallet to create a channel, its wallet  enforces that its user is the first participant
> 
> I don't think either of these solutions are great, given the current round-robin turn-taking semantics. The first peer in a 2-party channel always moves on turn 4; what if A wants to create an app channel where B moves first?

The "work-around" allows me to get both participants reliably creating channels for now in a stress test environment. I'm not suggesting that we implement that as a solution.

**Comment by andrewgordstewart** [comment]
Ah, in that case, it’s an easy work around indeed!

**Comment by lalexgap** [comment]
> Ah, in that case, it’s an easy work around indeed!

To solve this I think either:
- Participants need to  generate nonces co-operatively 
- Or we handle duplicate `channelIds` gracefully

But I haven't thought too much about it!

**Comment by andrewgordstewart** [comment]
So they can actually cooperatively generate unique nonces without communication overhead! Say we have two peers in a channel. They can always choose a nonce satisfying `nonce % numPeers = index` where `index` is their index in the sorted array of signing addresses.

This would require some changes around nonce management in the DB though. It seems like it's not a priority to fix it -- handling the error gracefully might be simpler?

**Comment by lalexgap** [comment]
> So they can actually cooperatively generate unique nonces without communication overhead! Say we have two peers in a channel. They can always choose a nonce satisfying `nonce % numPeers = index` where `index` is their index in the sorted array of signing addresses.

Clever!

> This would require some changes around nonce management in the DB though. It seems like it's not a priority to fix it -- handling the error gracefully might be simpler?

I think error handling might be tricky? It's possible that both participants create a channel at the same time that ends up with the same `channelId`.  It seems non-trivial deciding which channel is "real" and should be kept and which one is the duplicate and should be thrown away.
