### ISSUE TITLE
Flickering test [nitro-protocol/concludeAndTransferAllAssets]

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/statechannels#3682]
This [test run](https://app.circleci.com/pipelines/github/statechannels/statechannels/13481/workflows/6486247a-fd48-4967-84a9-f823958a445e/jobs/66092) from def6f8c32e33b124da30692094ac3ec45f9c1246 failed:
```
@statechannels/nitro-protocol: Summary of all failing tests
@statechannels/nitro-protocol: FAIL test/contracts/NitroAdjudicator/concludeAndTransferAllAssets.test.ts (61.79 s)
@statechannels/nitro-protocol:   ● concludeAndTransferAllAssets › 100 TOK payouts
@statechannels/nitro-protocol:     processing response error (body="{\"id\":277,\"jsonrpc\":\"2.0\",\"result\":\"0xa443b061dcd69f4088bbdffcc18a3768525940f96881588dd17d541b8343b5fe\",\"error\":{\"message\":\"VM Exception while processing transaction: out of gas\",\"code\":-32000,\"data\":{\"0xa443b061dcd69f4088bbdffcc18a3768525940f96881588dd17d541b8343b5fe\":{\"error\":\"out of gas\",\"program_counter\":2053,\"return\":\"0x\"},\"stack\":\"RuntimeError: VM Exception while processing transaction: out of gas\\n    at Function.RuntimeError.fromResults (/home/circleci/project/node_modules/ganache-core/lib/utils/runtimeerror.js:94:13)\\n    at BlockchainDouble.processBlock (/home/circleci/project/node_modules/ganache-core/lib/blockchain_double.js:627:24)\\n    at runMicrotasks (<anonymous>)\\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\",\"name\":\"RuntimeError\"}}}", error={"code":-32000,"data":{"0xa443b061dcd69f4088bbdffcc18a3768525940f96881588dd17d541b8343b5fe":{"error":"out of gas","program_counter":2053,"return":"0x"},"stack":"RuntimeError: VM Exception while processing transaction: out of gas\n    at Function.RuntimeError.fromResults (/home/circleci/project/node_modules/ganache-core/lib/utils/runtimeerror.js:94:13)\n    at BlockchainDouble.processBlock (/home/circleci/project/node_modules/ganache-core/lib/blockchain_double.js:627:24)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","name":"RuntimeError"}}, requestBody="{\"method\":\"eth_sendTransaction\",\"params\":[{\"gas\":\"0x1160c\",\"from\":\"0xd9995bae12fee327256ffec1e3184d492bd94c31\",\"to\":\"0xa6dd34f3cea10d1f78c0b1f8c13efbabe5df9708\",\"data\":\"0x2fb1d270000000000000000000000000357faed9d8d2fe67cec3732532f14e9958d8f3812623dc5954e55b6f6701cc146a64ed4c1ae29b86a9622c24ffae6fec4a121d2900000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000064\"}],\"id\":277,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="http://localhost:8561", code=SERVER_ERROR, version=web/5.0.7)
@statechannels/nitro-protocol:       at Logger.Object.<anonymous>.Logger.makeError (../../node_modules/@ethersproject/logger/src.ts/index.ts:205:28)
@statechannels/nitro-protocol:       at Logger.Object.<anonymous>.Logger.throwError (../../node_modules/@ethersproject/logger/src.ts/index.ts:217:20)
@statechannels/nitro-protocol:       at ../../node_modules/@ethersproject/web/src.ts/index.ts:281:28
@statechannels/nitro-protocol:       at step (../../node_modules/@ethersproject/web/lib/index.js:33:23)
@statechannels/nitro-protocol:       at Object.next (../../node_modules/@ethersproject/web/lib/index.js:14:53)
@statechannels/nitro-protocol:       at fulfilled (../../node_modules/@ethersproject/web/lib/index.js:5:58)
@statechannels/nitro-protocol:           at runMicrotasks (<anonymous>)
@statechannels/nitro-protocol: Test Suites: 1 failed, 2 passed, 3 of 23 total
@statechannels/nitro-protocol: Tests:       1 failed, 42 passed, 43 total
@statechannels/nitro-protocol: Snapshots:   0 total
@statechannels/nitro-protocol: Time:        62.309 s
@statechannels/nitro-protocol: Ran all test suites.
@statechannels/nitro-protocol: error Command failed with exit code 1.
@statechannels/nitro-protocol: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@statechannels/nitro-protocol: error Command failed with exit code 1.
@statechannels/nitro-protocol: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@statechannels/nitro-protocol: error Command failed with exit code 1.
@statechannels/nitro-protocol: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run test:ci exited 1 in '@statechannels/nitro-protocol'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Exited with code exit status 1
```

It passed locally, and on re-running the circle test, it [passed in CI](https://app.circleci.com/pipelines/github/statechannels/statechannels/13481/workflows/1402e4df-e794-4694-8ac2-1802fc0e0fdc/jobs/66106) as well.

**Comment by andrewgordstewart** [comment]
I also found this flicker when running locally on 73ba11167b2f94a7c7f47b2652c21f5687e7bbc1.
```
 FAIL  test/contracts/MultiAssetHolder/deposit.test.ts (61.552 s)
  ● deposit › Deposits Tokens (expectedHeld = 1)

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false



      at test/contracts/MultiAssetHolder/deposit.test.ts:169:89
      at step (test/contracts/MultiAssetHolder/deposit.test.ts:37:23)
      at Object.next (test/contracts/MultiAssetHolder/deposit.test.ts:18:53)
      at fulfilled (test/contracts/MultiAssetHolder/deposit.test.ts:9:58)


Test Suites: 1 failed, 22 passed, 23 total
Tests:       1 failed, 183 passed, 184 total
Snapshots:   0 total
Time:        138.007 s
```

Re-running the entire test suite reproduced the failure in the issue description:
```
 FAIL  test/contracts/NitroAdjudicator/concludeAndTransferAllAssets.test.ts (72.766 s)
  ● concludeAndTransferAllAssets › 100 TOK payouts
```

**Comment by geoknee** [comment]
73ba111 looks good to me on first glance. However, if it introduces a flicker we ought to be a bit wary. The test failure you quoted looks like it might have been caused by a colliding random channel id (bearing in mind the tests run concurrently). That said, I think a collision remains unlikely even with the new approach to random channel ids.

**Comment by andrewgordstewart** [comment]
> [73ba111](https://github.com/statechannels/statechannels/commit/73ba11167b2f94a7c7f47b2652c21f5687e7bbc1) looks good to me on first glance. However, if it introduces a flicker we ought to be a bit wary. The test failure you quoted looks like it might have been caused by a colliding random channel id (bearing in mind the tests run concurrently). That said, I think a collision remains unlikely even with the new approach to random channel ids.

I actually ran into the same error on master, locally:
```
 FAIL  test/contracts/ERC20AssetHolder/deposit.test.ts (31.233 s)
  ● deposit › Deposits Tokens (amount < holdings < amount + expectedHeld)

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false
```

It may be caused by not having run `yarn` after switching branches -- I only ran `yarn contract:compile`.

**Comment by geoknee** [comment]
The `master` branch now includes a possible fix for this flicker. If we don't see another failure for a while, we can probably close this issue. Otherwise, please paste a link to any new fails on this thread.

**Comment by geoknee** [comment]
The fix was to override the `gasLimit` on the problematic transaction. That seems to have worked (for now), so closing this.

Perhaps there is some bug where the usual gas estimation is inaccurate?
